apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-deployment
  namespace: default
  labels:
    dashboards: grafana-deployment
spec:
  external:
    url: http://localhost:3000/
    apiKey:
      name: grafana-cloud-credentials
      key: e3eaa0dad16PS